config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'tasks', to: 'tasks#index'
  get 'tasks/new', to: 'tasks#new'
  post 'tasks/create', to: 'tasks#create'
  get 'tasks/:id', to: 'tasks#show', as: :task
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= simple_form_for @task do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :details %>
  <%= f.text_field :details %>
  <% if @task.new_record? == false%>
    <%= f.label :completed %>
    <%= f.check_box :completed %>
  <% else %>
  <% end %>
  <%= f.submit %>
<% end %>

app/views/tasks/edit.html.erb
<h1>Edit <%= @task.title %></h1>
<%= render "form", task: @task %>

<%= link_to "Back to list", tasks_path %>

app/views/tasks/index.html.erb
<h1>Index</h1>
<br>
<ul>
  <% @tasks.each do |task| %>
    <%= link_to(task_path(task)) do %>
      <h4><%= task.title %></h4>
      <p><%= task.details %></p>
    <% end %>
  <% end %>
</ul>

app/views/tasks/new.html.erb
<h1>Add a new task</h1>
<%= render "form", task: @task %>

<%= link_to "Back to list", tasks_path %>

app/views/tasks/show.html.erb
<h1><%= @task.title %></h1>
<br>
<p><%= @task.details %></p>
<% if @task.completed? %>
<p><strong>Done!</strong></p>
<% else %>
<p><strong>To do!</strong></p>
<% end %>

<%= link_to "Tasks index", tasks_path %>